name: Update new firmware request issue

on:
  issues:
    types:
      - opened

jobs:
  get-issue-fields:
    name: Get issue Fields
    runs-on: ubuntu-22.04
    if: "contains(github.event.issue.labels.*.name, 'new firmware')"
    steps:
      - run: |
          asdf
